### ISSUE TITLE
A question about the motivation of predicting the initial pose of each person at the first frame

### ISSUE THREAD

**Issue by 2019211753** [priorMDM/priorMDM#34]
In the 3.2 section, this paper presents:

> We note that in some datasets, such as HumanML3D, all motions are processed to start with the root at the origin and facing the same direction

However, when I extract the first four dimensions of data from the first frame of each motion sequence in the 263-dimensional dataset, I find that these values differ for each motion sequence.. Could you please help me understand this? Thank you in advance for your assistance!

**Comment by GuyTevet** [comment]
Hi @2019211753 
The first four dimensions out of 263 in HumanML3D represent the velocities of the character rather than the absolute locations. To extract the absolute xyz locations of the motion you should run:

https://github.com/priorMDM/priorMDM/blob/b64123fc580d567a45af3d12aaa02c7f7ec4cf0a/data_loaders/humanml/scripts/motion_process.py#L415

as in:

https://github.com/priorMDM/priorMDM/blob/b64123fc580d567a45af3d12aaa02c7f7ec4cf0a/sample/two_person_text2motion.py#L130

Then you will see that the trajectory always starts at the origin.

**Comment by 2019211753** [comment]
> Hi @2019211753 The first four dimensions out of 263 in HumanML3D represent the velocities of the character rather than the absolute locations. To extract the absolute xyz locations of the motion you should run:
> 
> https://github.com/priorMDM/priorMDM/blob/b64123fc580d567a45af3d12aaa02c7f7ec4cf0a/data_loaders/humanml/scripts/motion_process.py#L415
> 
> as in:
> 
> https://github.com/priorMDM/priorMDM/blob/b64123fc580d567a45af3d12aaa02c7f7ec4cf0a/sample/two_person_text2motion.py#L130
> 
> Then you will see that the trajectory always starts at the origin.

Thanks for your rapld reply! It solves my question.
